### ISSUE TITLE
elm make with debug flag

### ISSUE THREAD

**Issue by mordrax** [elm-community/SublimeElmLanguageSupport#33]
It looks like from the settings file that you can turn the `--debug` flag on when doing a build:
https://github.com/elm-community/Elm.tmLanguage/blob/master/Settings/Elm%20Language%20Support.sublime-settings

However, turning it on doesn't seem to have an effect on the output js file. 

Is there a way to add flags to the build?

**Comment by hippadrone** [comment]
This doesn't really fix your problem, but what I to get around it was this:

I went into Elm Make.sublime-build, and copied the Run variant... renamed it to Run- Debug, and added "--debug" to the list under cmd

I actually like it better than having to go into the settings because I can easily toggle it
