### ISSUE TITLE
Format on save makes Sublime 3.2 jump to top of file

### ISSUE THREAD

**Issue by woylie** [elm-community/SublimeElmLanguageSupport#65]
I just upgraded Sublime to 3.2 and have `elm_format_on_save` set to true. When I save a file now, Sublime scrolls to the top of the file most of the time. I did not encounter that behavior with the format-on-save option in the [Elixir package](https://github.com/elixir-editors/elixir-tmbundle/issues).

I thought this might be related to the new Git features, but this even occurs with `mini_diff` and `show_git_status` set to false.

**Comment by ivanbanov** [comment]
Yeah, Im facing the same problem :(
![jumpy](https://user-images.githubusercontent.com/2953018/54376411-4d1e4400-4683-11e9-8913-d9458fad7dc3.gif)

**Comment by ringvold** [comment]
Are there any updates on this?

**Comment by sentience** [comment]
@ringvold I haven't had a chance to take a look at this, no. Honestly, I was hoping it was a bug in a recent build of Sublime and that it would be fixed in a subsequent release. From your question, I take it the problem hasn't gone away.

If anyone else wants to take a look at this and figure out what's wrong, I'd appreciate the contribution! Otherwise, I'll try to take a look sometime in the next few weeks.

**Comment by ivanbanov** [comment]
Just as a workaround I've disabled the autoformat option
```json
{ "elm_format_on_save": false }
```
and then running on terminal
```
npx onchange '**/*.elm' -- elm-format {{changed}} --yes
```

:)

**Comment by woylie** [comment]
Closing this since this doesn't seem to be an issue anymore.
